apiVersion: v1
kind: Service
metadata:
  name: ee-flask-app
spec:
  selector:
    app: ee-flask-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000  # Explicitly set the NodePort
  type: NodePort