name: 'Build and Push Docker Image'
description: 'Build and Push Docker Image to GHCR'

inputs:
  image_name:
    description: 'The name of the Docker image to build and push.'
    required: true
  registry_type:
    description: 'The type of registry: "local" or "dockerhub".'
    required: true
    default: 'local'

runs:
  using: "composite"
  steps:
    # Push to Local Container Registry

    - name: Start Local Container Registry
      if: ${{ github.event.act }}
      shell: bash
      run: |
        if ! docker ps --filter "status=running" --format "{{.Ports}}" | grep -q ":5000->"; then
          echo "Starting local container registry..."
          docker run -d -p 5000:5000 registry:2
        else
          echo "Local container registry is already running."
        fi

    - name: Build Docker Locally Image
      if: ${{ github.event.act }}
      shell: bash
      run: |
        if [ "${{ inputs.registry_type }}" == "local" ]; then
          docker build -t localhost:5000/${{ inputs.image_name }} .
        else
          docker build -t ${{ inputs.image_name }} .
        fi

    - name: Push to Local Registry
      shell: bash
      if: ${{ github.event.act }}
      run: |
        docker push localhost:5000/${{ inputs.image_name }}

    # Push to Remote Container Registry

    - name: Log in to Docker Hub
      if: ${{ !github.event.act }}
      uses: docker/login-action@v2
      with:
        username: username
        password: password

    - name: Set up Docker Buildx
      if: ${{ !github.event.act }}
      uses: docker/setup-buildx-action@v2

    - name: Generate Docker Tags
      if: ${{ !github.event.act }}
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: username/ee
        tags: |
          type=sha

    - name: Build and Push Docker Image
      if: ${{ !github.event.act }}
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - name: Log out from Docker Hub
      if: ${{ !github.event.act }}
      shell: bash
      run: docker logout